// Ordered from most-specific compound phrases to single keywords.
// First match wins, so put longer/more specific phrases before shorter ones.
const RULES: [string, string][] = [
  // ── Soups (before "cream", "chicken", "mushroom" single-word rules) ──
  ["cream of mushroom", "🍄"],
  ["cream of chicken", "🍗"],
  ["cream of celery", "🌿"],
  ["french onion soup", "🧅"],

  // ── Specific compounds (before their component words) ──
  ["sweet potato", "🍠"],
  ["bell pepper", "🫑"],
  ["chili pepper", "🌶️"],
  ["black pepper", "🧂"],
  ["white pepper", "🧂"],
  ["red pepper flake", "🌶️"],
  ["cayenne pepper", "🌶️"],
  ["hot pepper", "🌶️"],
  ["banana pepper", "🌶️"],
  ["peanut butter", "🥜"],
  ["almond butter", "🌰"],
  ["apple butter", "🍎"],
  ["apple cider", "🍎"],
  ["apple juice", "🍎"],
  ["apple sauce", "🍎"],
  ["olive oil", "🫒"],
  ["coconut oil", "🥥"],
  ["coconut milk", "🥥"],
  ["coconut cream", "🥥"],
  ["coconut water", "🥥"],
  ["coconut flake", "🥥"],
  ["soy sauce", "🫙"],
  ["soy milk", "🫘"],
  ["maple syrup", "🍁"],
  ["maple sugar", "🍁"],
  ["balsamic vinegar", "🫙"],
  ["rice vinegar", "🫙"],
  ["apple cider vinegar", "🫙"],
  ["hot sauce", "🌶️"],
  ["worcestershire sauce", "🫙"],
  ["fish sauce", "🐟"],
  ["oyster sauce", "🦪"],
  ["hoisin sauce", "🫙"],
  ["teriyaki sauce", "🫙"],
  ["barbecue sauce", "🍖"],
  ["bbq sauce", "🍖"],
  ["pasta sauce", "🍝"],
  ["tomato sauce", "🍅"],
  ["tomato paste", "🍅"],
  ["tomato puree", "🍅"],
  ["diced tomato", "🍅"],
  ["crushed tomato", "🍅"],
  ["sun dried tomato", "🍅"],
  ["ground beef", "🥩"],
  ["ground pork", "🥩"],
  ["ground turkey", "🦃"],
  ["ground lamb", "🥩"],
  ["ground chicken", "🍗"],
  ["ground veal", "🥩"],
  ["chicken breast", "🍗"],
  ["chicken thigh", "🍗"],
  ["chicken wing", "🍗"],
  ["chicken leg", "🍗"],
  ["chicken stock", "🍗"],
  ["chicken broth", "🍗"],
  ["beef broth", "🥩"],
  ["beef stock", "🥩"],
  ["beef bouillon", "🥩"],
  ["pork belly", "🥓"],
  ["pork chop", "🥩"],
  ["pork loin", "🥩"],
  ["pork shoulder", "🥩"],
  ["pork tenderloin", "🥩"],
  ["pork rind", "🥓"],
  ["cream cheese", "🧀"],
  ["cottage cheese", "🧀"],
  ["sour cream", "🥛"],
  ["heavy cream", "🥛"],
  ["whipping cream", "🥛"],
  ["half and half", "🥛"],
  ["condensed milk", "🥛"],
  ["evaporated milk", "🥛"],
  ["buttermilk", "🥛"],
  ["skim milk", "🥛"],
  ["whole milk", "🥛"],
  ["almond milk", "🌰"],
  ["oat milk", "🌾"],
  ["ice cream", "🍨"],
  ["whipped cream", "🍦"],
  ["star anise", "🌿"],
  ["pine nut", "🌰"],
  ["poppy seed", "🌸"],
  ["sesame seed", "🌾"],
  ["sunflower seed", "🌻"],
  ["pumpkin seed", "🎃"],
  ["chia seed", "🌾"],
  ["flax seed", "🌾"],
  ["flaxseed", "🌾"],
  ["graham cracker", "🍪"],
  ["bread crumb", "🍞"],
  ["bread cube", "🍞"],
  ["pie shell", "🥧"],
  ["pie crust", "🥧"],
  ["pastry shell", "🥧"],
  ["pizza crust", "🍕"],
  ["pizza dough", "🍕"],
  ["puff pastry", "🥐"],
  ["phyllo dough", "🥐"],
  ["filo dough", "🥐"],
  ["flour tortilla", "🫓"],
  ["corn tortilla", "🫓"],
  ["pita bread", "🫓"],
  ["flat bread", "🫓"],
  ["sourdough", "🍞"],
  ["baking powder", "🥄"],
  ["baking soda", "🥄"],
  ["active dry yeast", "🍞"],
  ["instant yeast", "🍞"],
  ["vanilla extract", "🍶"],
  ["vanilla bean", "🍶"],
  ["vanilla pod", "🍶"],
  ["lemon zest", "🍋"],
  ["lemon juice", "🍋"],
  ["lime juice", "🍋"],
  ["orange juice", "🍊"],
  ["orange zest", "🍊"],
  ["grapefruit juice", "🍊"],
  ["passion fruit", "🍈"],
  ["dragon fruit", "🍈"],
  ["star fruit", "🍈"],
  ["green onion", "🌿"],
  ["spring onion", "🌿"],
  ["red onion", "🧅"],
  ["white onion", "🧅"],
  ["yellow onion", "🧅"],
  ["pearl onion", "🧅"],
  ["pickled onion", "🧅"],
  ["garlic powder", "🧄"],
  ["garlic clove", "🧄"],
  ["garlic salt", "🧄"],
  ["garlic oil", "🧄"],
  ["white wine", "🍾"],
  ["red wine", "🍷"],
  ["rosé wine", "🍷"],
  ["white wine vinegar", "🫙"],
  ["red wine vinegar", "🫙"],
  ["rice wine", "🍶"],
  ["cooking wine", "🍷"],
  ["instant coffee", "☕"],
  ["instant espresso", "☕"],
  ["green tea", "🍵"],
  ["black tea", "🍵"],
  ["herbal tea", "🍵"],
  ["brown sugar", "🍬"],
  ["powdered sugar", "🍬"],
  ["icing sugar", "🍬"],
  ["caster sugar", "🍬"],
  ["raw sugar", "🍬"],
  ["agave nectar", "🌵"],
  ["agave syrup", "🌵"],
  ["corn syrup", "🌽"],
  ["corn starch", "🌽"],
  ["cornstarch", "🌽"],
  ["cornmeal", "🌽"],
  ["corn flour", "🌽"],
  ["oat flour", "🌾"],
  ["wheat flour", "🌾"],
  ["almond flour", "🌰"],
  ["rice flour", "🍚"],
  ["chickpea flour", "🫘"],
  ["gram flour", "🫘"],
  ["bread flour", "🍞"],
  ["self raising flour", "🌾"],
  ["all purpose flour", "🌾"],
  ["whole wheat flour", "🌾"],
  ["chocolate chip", "🍫"],
  ["dark chocolate", "🍫"],
  ["milk chocolate", "🍫"],
  ["white chocolate", "🍫"],
  ["cocoa powder", "🍫"],
  ["cocoa butter", "🍫"],
  ["cacao powder", "🍫"],
  ["caramel sauce", "🍮"],
  ["dulce de leche", "🍮"],
  ["peanut oil", "🥜"],
  ["sesame oil", "🌾"],
  ["truffle oil", "🍄"],
  ["canola oil", "🫙"],
  ["vegetable oil", "🫙"],
  ["cooking spray", "🫙"],
  ["nonstick spray", "🫙"],
  ["blue cheese", "🧀"],
  ["cheddar cheese", "🧀"],
  ["parmesan cheese", "🧀"],
  ["mozzarella cheese", "🧀"],
  ["feta cheese", "🧀"],
  ["goat cheese", "🧀"],
  ["gouda cheese", "🧀"],
  ["swiss cheese", "🧀"],
  ["ricotta cheese", "🧀"],
  ["brie cheese", "🧀"],
  ["provolone cheese", "🧀"],
  ["monterey jack cheese", "🧀"],
  ["american cheese", "🧀"],
  ["string cheese", "🧀"],
  ["pepper jack", "🧀"],
  ["gruyere", "🧀"],
  ["gruyère", "🧀"],
  ["parmesan", "🧀"],
  ["mozzarella", "🧀"],
  ["pecorino", "🧀"],
  ["manchego", "🧀"],
  ["brie", "🧀"],
  ["camembert", "🧀"],
  ["roquefort", "🧀"],
  ["gorgonzola", "🧀"],
  ["emmental", "🧀"],
  ["asiago", "🧀"],
  ["fontina", "🧀"],
  ["ricotta", "🧀"],
  ["mascarpone", "🧀"],

  // ── Fruits ──
  ["strawberry", "🍓"],
  ["blueberry", "🫐"],
  ["blackberry", "🫐"],
  ["raspberry", "🫐"],
  ["cranberry", "🍒"],
  ["gooseberry", "🫐"],
  ["elderberry", "🫐"],
  ["boysenberry", "🫐"],
  ["huckleberry", "🫐"],
  ["mulberry", "🫐"],
  ["watermelon", "🍉"],
  ["cantaloupe", "🍈"],
  ["honeydew", "🍈"],
  ["pineapple", "🍍"],
  ["grapefruit", "🍊"],
  ["tangerine", "🍊"],
  ["mandarin", "🍊"],
  ["clementine", "🍊"],
  ["pomelo", "🍊"],
  ["lychee", "🍈"],
  ["longan", "🍈"],
  ["rambutan", "🍈"],
  ["jackfruit", "🍈"],
  ["breadfruit", "🍈"],
  ["papaya", "🍈"],
  ["guava", "🍈"],
  ["tamarind", "🍈"],
  ["persimmon", "🍊"],
  ["quince", "🍐"],
  ["pomegranate", "🍎"],
  ["nectarine", "🍑"],
  ["apricot", "🍑"],
  ["plum", "🍑"],
  ["prune", "🍑"],
  ["cherry", "🍒"],
  ["peach", "🍑"],
  ["mango", "🥭"],
  ["avocado", "🥑"],
  ["coconut", "🥥"],
  ["banana", "🍌"],
  ["plantain", "🍌"],
  ["kiwi", "🥝"],
  ["lemon", "🍋"],
  ["lime", "🍋"],
  ["orange", "🍊"],
  ["apple", "🍎"],
  ["pear", "🍐"],
  ["grape", "🍇"],
  ["raisin", "🍇"],
  ["currant", "🍇"],
  ["fig", "🍇"],
  ["date", "🌴"],
  ["melon", "🍈"],
  ["tomato", "🍅"],
  ["tomatillo", "🍅"],

  // ── Vegetables ──
  ["artichoke", "🌿"],
  ["asparagus", "🥦"],
  ["aubergine", "🍆"],
  ["eggplant", "🍆"],
  ["broccoli", "🥦"],
  ["cauliflower", "🥦"],
  ["brussels sprout", "🥦"],
  ["butternut squash", "🎃"],
  ["acorn squash", "🎃"],
  ["spaghetti squash", "🎃"],
  ["butternut", "🎃"],
  ["pumpkin", "🎃"],
  ["squash", "🎃"],
  ["zucchini", "🥒"],
  ["courgette", "🥒"],
  ["cucumber", "🥒"],
  ["watercress", "🥬"],
  ["bok choy", "🥬"],
  ["pak choi", "🥬"],
  ["spinach", "🥬"],
  ["kale", "🥬"],
  ["arugula", "🥬"],
  ["lettuce", "🥬"],
  ["cabbage", "🥬"],
  ["chard", "🥬"],
  ["collard", "🥬"],
  ["endive", "🥬"],
  ["radicchio", "🥬"],
  ["escarole", "🥬"],
  ["celery", "🌿"],
  ["fennel", "🌿"],
  ["leek", "🧅"],
  ["shallot", "🧅"],
  ["scallion", "🌿"],
  ["chive", "🌿"],
  ["carrot", "🥕"],
  ["parsnip", "🥕"],
  ["beet", "🌿"],
  ["beetroot", "🌿"],
  ["radish", "🌿"],
  ["daikon", "🌿"],
  ["turnip", "🌿"],
  ["rutabaga", "🌿"],
  ["kohlrabi", "🌿"],
  ["jicama", "🌿"],
  ["yuca", "🌿"],
  ["cassava", "🌿"],
  ["taro", "🌿"],
  ["yam", "🍠"],
  ["potato", "🥔"],
  ["corn", "🌽"],
  ["maize", "🌽"],
  ["okra", "🌿"],
  ["mushroom", "🍄"],
  ["truffle", "🍄"],
  ["onion", "🧅"],
  ["garlic", "🧄"],
  ["pepper", "🫑"],

  // ── Legumes ──
  ["edamame", "🫛"],
  ["chickpea", "🫘"],
  ["lentil", "🫘"],
  ["hummus", "🫘"],
  ["tofu", "🫘"],
  ["tempeh", "🫘"],
  ["miso", "🫘"],
  ["bean", "🫘"],
  ["pea", "🫛"],
  ["soy", "🫘"],

  // ── Herbs ──
  ["basil", "🌿"],
  ["oregano", "🌿"],
  ["thyme", "🌿"],
  ["rosemary", "🌿"],
  ["parsley", "🌿"],
  ["cilantro", "🌿"],
  ["coriander", "🌿"],
  ["mint", "🌿"],
  ["sage", "🌿"],
  ["dill", "🌿"],
  ["tarragon", "🌿"],
  ["marjoram", "🌿"],
  ["chervil", "🌿"],
  ["sorrel", "🌿"],
  ["lovage", "🌿"],
  ["lemongrass", "🌿"],
  ["bay leaf", "🌿"],
  ["bay", "🌿"],

  // ── Spices ──
  ["turmeric", "🌿"],
  ["saffron", "🌿"],
  ["paprika", "🌶️"],
  ["cayenne", "🌶️"],
  ["chili", "🌶️"],
  ["chile", "🌶️"],
  ["jalapeño", "🌶️"],
  ["jalapeno", "🌶️"],
  ["habanero", "🌶️"],
  ["serrano", "🌶️"],
  ["chipotle", "🌶️"],
  ["cumin", "🌿"],
  ["caraway", "🌿"],
  ["fennel seed", "🌿"],
  ["fenugreek", "🌿"],
  ["mustard seed", "🌿"],
  ["cardamom", "🌿"],
  ["nutmeg", "🌰"],
  ["mace", "🌰"],
  ["clove", "🌰"],
  ["allspice", "🌰"],
  ["cinnamon", "🌰"],
  ["ginger", "🌿"],
  ["wasabi", "🌿"],
  ["horseradish", "🌿"],
  ["sumac", "🌿"],
  ["za'atar", "🌿"],
  ["harissa", "🌶️"],
  ["achiote", "🌿"],
  ["annatto", "🌿"],
  ["ajwain", "🌿"],
  ["asafoetida", "🌿"],
  ["vanilla", "🍶"],
  ["salt", "🧂"],

  // ── Nuts ──
  ["almond", "🌰"],
  ["walnut", "🌰"],
  ["pecan", "🌰"],
  ["chestnut", "🌰"],
  ["hazelnut", "🌰"],
  ["cashew", "🌰"],
  ["pistachio", "🌰"],
  ["macadamia", "🌰"],
  ["brazil nut", "🌰"],
  ["peanut", "🥜"],
  ["groundnut", "🥜"],
  ["tahini", "🌰"],

  // ── Grains, bread & pasta ──
  ["spaghetti", "🍝"],
  ["fettuccine", "🍝"],
  ["linguine", "🍝"],
  ["pappardelle", "🍝"],
  ["tagliatelle", "🍝"],
  ["rigatoni", "🍝"],
  ["penne", "🍝"],
  ["fusilli", "🍝"],
  ["rotini", "🍝"],
  ["farfalle", "🍝"],
  ["orzo", "🍝"],
  ["lasagna", "🍝"],
  ["ravioli", "🍝"],
  ["tortellini", "🍝"],
  ["gnocchi", "🍝"],
  ["pasta", "🍝"],
  ["noodle", "🍜"],
  ["ramen", "🍜"],
  ["udon", "🍜"],
  ["soba", "🍜"],
  ["rice noodle", "🍜"],
  ["glass noodle", "🍜"],
  ["vermicelli", "🍜"],
  ["rice", "🍚"],
  ["risotto", "🍚"],
  ["arborio", "🍚"],
  ["basmati", "🍚"],
  ["jasmine rice", "🍚"],
  ["brown rice", "🍚"],
  ["wild rice", "🍚"],
  ["couscous", "🌾"],
  ["polenta", "🌽"],
  ["grits", "🌽"],
  ["oat", "🌾"],
  ["barley", "🌾"],
  ["quinoa", "🌾"],
  ["millet", "🌾"],
  ["buckwheat", "🌾"],
  ["bulgur", "🌾"],
  ["farro", "🌾"],
  ["spelt", "🌾"],
  ["rye", "🌾"],
  ["wheat", "🌾"],
  ["flour", "🌾"],
  ["sourdough", "🍞"],
  ["brioche", "🍞"],
  ["baguette", "🥖"],
  ["focaccia", "🍞"],
  ["ciabatta", "🍞"],
  ["bread", "🍞"],
  ["toast", "🍞"],
  ["crouton", "🍞"],
  ["cracker", "🍘"],
  ["tortilla", "🫓"],
  ["pita", "🫓"],
  ["naan", "🫓"],
  ["lavash", "🫓"],
  ["matzo", "🫓"],
  ["bagel", "🥯"],
  ["muffin", "🧁"],
  ["croissant", "🥐"],
  ["pretzel", "🥨"],
  ["waffle", "🧇"],
  ["pancake", "🥞"],
  ["crepe", "🥞"],

  // ── Dairy ──
  ["yogurt", "🥛"],
  ["yoghurt", "🥛"],
  ["kefir", "🥛"],
  ["ghee", "🧈"],
  ["butter", "🧈"],
  ["cheese", "🧀"],
  ["milk", "🥛"],
  ["cream", "🥛"],
  ["whey", "🥛"],

  // ── Eggs ──
  ["egg", "🥚"],

  // ── Meat ──
  ["prosciutto", "🥩"],
  ["pancetta", "🥓"],
  ["salami", "🥩"],
  ["chorizo", "🌶️"],
  ["pepperoni", "🍕"],
  ["sausage", "🌭"],
  ["hot dog", "🌭"],
  ["hotdog", "🌭"],
  ["bratwurst", "🌭"],
  ["kielbasa", "🌭"],
  ["bacon", "🥓"],
  ["ham", "🥩"],
  ["prawn", "🦐"],
  ["shrimp", "🦐"],
  ["lobster", "🦞"],
  ["crab", "🦀"],
  ["clam", "🦪"],
  ["oyster", "🦪"],
  ["mussel", "🦪"],
  ["scallop", "🦪"],
  ["calamari", "🦑"],
  ["squid", "🦑"],
  ["octopus", "🐙"],
  ["salmon", "🐟"],
  ["tuna", "🐟"],
  ["cod", "🐟"],
  ["halibut", "🐟"],
  ["trout", "🐟"],
  ["sardine", "🐟"],
  ["anchovy", "🐟"],
  ["herring", "🐟"],
  ["mackerel", "🐟"],
  ["tilapia", "🐟"],
  ["flounder", "🐟"],
  ["catfish", "🐟"],
  ["snapper", "🐟"],
  ["mahi", "🐟"],
  ["sea bass", "🐟"],
  ["ahi", "🐟"],
  ["fish", "🐟"],
  ["seafood", "🦐"],
  ["turkey", "🦃"],
  ["duck", "🦆"],
  ["goose", "🦆"],
  ["quail", "🍗"],
  ["pheasant", "🍗"],
  ["chicken", "🍗"],
  ["lamb", "🥩"],
  ["mutton", "🥩"],
  ["veal", "🥩"],
  ["venison", "🥩"],
  ["bison", "🥩"],
  ["elk", "🥩"],
  ["game", "🥩"],
  ["pork", "🥩"],
  ["beef", "🥩"],
  ["steak", "🥩"],
  ["meat", "🥩"],
  ["lard", "🥓"],

  // ── Oils, fats, vinegar ──
  ["olive", "🫒"],
  ["oil", "🫙"],
  ["vinegar", "🫙"],
  ["mustard", "🌿"],

  // ── Sweeteners & confection ──
  ["chocolate", "🍫"],
  ["cocoa", "🍫"],
  ["cacao", "🍫"],
  ["caramel", "🍮"],
  ["dulce de leche", "🍮"],
  ["honey", "🍯"],
  ["molasses", "🍯"],
  ["treacle", "🍯"],
  ["syrup", "🍯"],
  ["jam", "🫙"],
  ["jelly", "🫙"],
  ["marmalade", "🫙"],
  ["preserves", "🫙"],
  ["sugar", "🍬"],
  ["agave", "🌵"],
  ["stevia", "🌿"],
  ["saccharin", "🍬"],
  ["sweetener", "🍬"],

  // ── Alcohol ──
  ["champagne", "🍾"],
  ["prosecco", "🍾"],
  ["sparkling wine", "🍾"],
  ["whiskey", "🥃"],
  ["whisky", "🥃"],
  ["bourbon", "🥃"],
  ["scotch", "🥃"],
  ["rum", "🥃"],
  ["vodka", "🥃"],
  ["tequila", "🥃"],
  ["mezcal", "🥃"],
  ["cognac", "🥃"],
  ["brandy", "🥃"],
  ["gin", "🍸"],
  ["liqueur", "🍸"],
  ["schnapps", "🥃"],
  ["vermouth", "🍸"],
  ["wine", "🍷"],
  ["stout", "🍺"],
  ["porter", "🍺"],
  ["lager", "🍺"],
  ["pilsner", "🍺"],
  ["ale", "🍺"],
  ["beer", "🍺"],
  ["cider", "🍺"],
  ["sake", "🍶"],
  ["mirin", "🍶"],

  // ── Hot drinks ──
  ["espresso", "☕"],
  ["coffee", "☕"],
  ["tea", "🍵"],

  // ── Soft drinks & misc ──
  ["lemonade", "🍋"],
  ["juice", "🧃"],
  ["soda", "🥤"],
  ["cola", "🥤"],
  ["lemon lime", "🥤"],
  ["broth", "🍲"],
  ["stock", "🍲"],
  ["bouillon", "🍲"],
  ["gelatin", "🥄"],
  ["agar", "🥄"],
  ["starch", "🌾"],
  ["water", "💧"],
  ["ice", "🧊"],
];

export function getIngredientEmoji(name: string): string {
  const lower = name.toLowerCase();
  for (const [kw, emoji] of RULES) {
    if (lower.includes(kw)) return emoji;
  }
  return "🌿";
}

// Deterministic color from ingredient name — dark hue for the card background.
export function getIngredientColor(name: string): string {
  let h = 0;
  for (let i = 0; i < name.length; i++) {
    h = (h * 31 + name.charCodeAt(i)) >>> 0;
  }
  return `hsl(${h % 360}, 45%, 20%)`;
}
